export { default as HomePage } from './Home'
export { default as LoginPage } from './Login'
export { default as AboutPage } from './About'
export { default as MessagePage } from './Message'
export { default as NewHome } from './NewHome'